
CREATE SEQUENCE ID_SEQ START WITH 1;

CREATE TABLE TIME_ZONE(
    ID bigint PRIMARY KEY,
    NAME VARCHAR NOT NULL);

CREATE TABLE SUBDIVISION_PU(
ID bigint PRIMARY KEY ,
NAME VARCHAR NOT NULL);

CREATE TABLE COMPANY(
id bigint PRIMARY KEY,
SHORT_NAME VARCHAR,
FULL_NAME VARCHAR,
LEGAL_ADRESS VARCHAR,
ACTUAL_ADRESS VARCHAR,
INN VARCHAR (12),
KPP VARCHAR (9),
FIAS VARCHAR,
PHONE VARCHAR (30),
ACTUAL BOOLEAN,
VIP VARCHAR,
TIME_ZONE_ID BIGINT,
WORK_FROM time without time zone,
WORK_UNTIL time without time zone,
LUNCH_FROM TIME,
LUNCH_UNTIL TIME,
SUBDIVISION_DE_ID BIGINT,
PU_ID BIGINT,
NOTE VARCHAR);

alter table COMPANY add constraint fk_1 foreign key (TIME_ZONE_ID) REFERENCES TIME_ZONE (ID);
alter table COMPANY add constraint fk_2 foreign key (PU_ID) REFERENCES SUBDIVISION_PU (ID);

CREATE TABLE USER_TABLE(
id bigint PRIMARY KEY,
USER_NAME VARCHAR,
MOBILE_PHONE VARCHAR,
WORK_PHONE VARCHAR,
SKYPE VARCHAR,
ICQ VARCHAR,
POSITION VARCHAR,
COMPANY_ID BIGINT,
BLOCKING_CAUSE VARCHAR);

alter table USER_TABLE add constraint fk_3 foreign key (COMPANY_ID) REFERENCES COMPANY (ID);


);